// packages/angular/src/lib/dental-draft-editor.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectorRef, Component, EventEmitter, Input, OnChanges, Output, inject } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { MindBillAngularAppearance, mindBillAngularAppearanceStyle } from "./appearance";
import { treatmentDraftStyle } from "./treatment-draft-style";
import { treatmentDraftKey } from "./submission-treatment";
import { DentalDraftContentInput, DentalDraftLineInput, dentalDraftChargeSummary, parseDentalCharge, validateDentalDraftContent } from "./treatment-drafts";

@Component({
  selector: "mindbill-dental-draft-editor", standalone: true, imports: [CommonModule, FormsModule], styles: [treatmentDraftStyle],
  template: `@if (draft) { <form class="mbtd" [ngStyle]="theme" (ngSubmit)="save()">
    <h2>Prepare a dental bill</h2><p>Save a draft for review. Unknown charges can stay blank.</p>
    <fieldset [disabled]="disabled || busy"><label>Diagnosis codes (comma separated)<input name="diagnoses" [(ngModel)]="diagnoses" /></label>
    <label>Notes<textarea name="notes" [ngModel]="draft.notes" (ngModelChange)="draft.notes = $event.trim() || null" maxlength="5000"></textarea></label>
    @for (line of draft.lines; track line; let i = $index) { <fieldset><legend>Service {{ i + 1 }}</legend><div class="mbtd-grid">
      <label>CDT code<input [name]="'code'+i" [ngModel]="line.code" (ngModelChange)="line.code = $event.trim().toUpperCase() || null" placeholder="D0120" maxlength="5" /></label>
      <label>Edition year<input type="number" [name]="'year'+i" [(ngModel)]="line.editionYear" min="1900" max="2200" step="1" /></label>
      <label>Service date<input type="date" [name]="'date'+i" [ngModel]="line.serviceDate" (ngModelChange)="line.serviceDate = $event || null" /></label>
      <label>Quantity<input type="number" [name]="'quantity'+i" [(ngModel)]="line.quantity" min="1" max="100000" step="1" /></label>
      <label>Extended charge ($)<input inputmode="decimal" [name]="'charge'+i" [(ngModel)]="charges[i]" placeholder="Unknown" /></label>
      <label>Charge reference<input [name]="'reference'+i" [ngModel]="line.chargeReference" (ngModelChange)="line.chargeReference = $event.trim() || null" maxlength="1000" /></label>
      <label>Teeth (comma separated)<input [name]="'teeth'+i" [(ngModel)]="teeth[i]" /></label>
      <label>Surfaces (comma separated)<input [name]="'surfaces'+i" [(ngModel)]="surfaces[i]" /></label>
      <label>Oral cavity<input [name]="'cavity'+i" [ngModel]="line.oralCavity" (ngModelChange)="line.oralCavity = $event.trim() || null" maxlength="100" /></label>
      <label>Description<textarea [name]="'description'+i" [ngModel]="line.description" (ngModelChange)="line.description = $event.trim() || null" maxlength="1000"></textarea></label>
      <label>Prosthesis notes<textarea [name]="'prosthesis'+i" [ngModel]="line.prosthesisNotes" (ngModelChange)="line.prosthesisNotes = $event.trim() || null" maxlength="2000"></textarea></label>
    </div><button type="button" (click)="removeLine(i)">Remove service</button></fieldset> }
    <p>{{ chargeSummary }}</p><div class="mbtd-actions"><button type="button" (click)="addLine()" [disabled]="draft.lines.length >= 100">Add service</button>
    <button class="mbtd-primary" type="submit">{{ busy ? 'Saving…' : 'Save draft' }}</button></div></fieldset>
    @if (error) { <p role="alert">{{ error }}</p> } @if (success) { <p role="status">Draft saved.</p> }
    <footer class="mbtd-attribution"><a href="https://mindbill.org" target="_blank" rel="noopener noreferrer">Powered by MindBill</a></footer>
  </form> }`,
})
export class DentalDraftEditorComponent implements OnChanges {
  @Input({ required: true }) initialContent!: DentalDraftContentInput;
  @Input({ required: true }) onSave!: (content: DentalDraftContentInput) => Promise<unknown>;
  @Input() disabled = false;
  @Input() appearance?: MindBillAngularAppearance;
  @Output() saved = new EventEmitter<DentalDraftContentInput>();
  @Output() saveError = new EventEmitter<Error>();
  draft?: DentalDraftContentInput;
  diagnoses = ""; charges: string[] = []; teeth: string[] = []; surfaces: string[] = [];
  busy = false; error = ""; success = false;
  private initialKey = "";
  private readonly detector = inject(ChangeDetectorRef);
  get theme() { return mindBillAngularAppearanceStyle(this.appearance); }
  ngOnChanges() { const key = treatmentDraftKey(this.initialContent); if (this.initialContent && key !== this.initialKey) { this.initialKey = key; this.draft = structuredClone(this.initialContent); this.diagnoses = this.draft.diagnosisCodes.join(", "); this.charges = this.draft.lines.map(line => line.chargeCents === null ? "" : (line.chargeCents / 100).toFixed(2)); this.teeth = this.draft.lines.map(line => line.teeth.join(", ")); this.surfaces = this.draft.lines.map(line => line.surfaces.join(", ")); this.error = ""; this.success = false; } }
  private list(value: string) { return value.split(",").map(item => item.trim()).filter(Boolean); }
  private content(): DentalDraftContentInput { return { ...structuredClone(this.draft!), diagnosisCodes: this.list(this.diagnoses), lines: this.draft!.lines.map((line, i) => ({ ...structuredClone(line), chargeCents: parseDentalCharge(this.charges[i] ?? ""), teeth: this.list(this.teeth[i] ?? ""), surfaces: this.list(this.surfaces[i] ?? "") })) }; }
  get chargeSummary() { if (!this.draft) return ""; try { const summary = dentalDraftChargeSummary(this.content().lines); const dollars = (summary.knownChargeCents / 100).toLocaleString("en-US", { style: "currency", currency: "USD" }); return summary.totalChargeCents === null ? `Known charges: ${dollars} · Total incomplete` : `Total charges: ${dollars}`; } catch { return "Check the extended charges."; } }
  addLine() { if (!this.draft || this.draft.lines.length >= 100) return; const line: DentalDraftLineInput = { code: null, description: null, editionYear: null, serviceDate: null, quantity: 1, chargeCents: null, chargeReference: null, teeth: [], surfaces: [], oralCavity: null, prosthesisNotes: null }; this.draft.lines.push(line); this.charges.push(""); this.teeth.push(""); this.surfaces.push(""); }
  removeLine(index: number) { this.draft?.lines.splice(index, 1); this.charges.splice(index, 1); this.teeth.splice(index, 1); this.surfaces.splice(index, 1); }
  async save() {
    if (!this.draft || this.disabled || this.busy) return;
    this.success = false; let content: DentalDraftContentInput;
    try { content = this.content(); this.error = validateDentalDraftContent(content) ?? ""; } catch (error) { this.error = error instanceof Error ? error.message : "Check the extended charges."; return; }
    if (this.error) return;
    this.busy = true;
    try { await this.onSave(content); this.saved.emit(content); this.success = true; }
    catch { this.error = "Could not save the draft. Please try again."; this.saveError.emit(new Error(this.error)); }
    finally { this.busy = false; this.detector.markForCheck(); }
  }
}

// packages/react/src/dental-draft-editor.tsx
"use client";
import { useState, type ReactElement } from "react";
import { isDraftDate, TreatmentDraftShell, useDraftSave, type TreatmentDraftAppearance } from "./treatment-draft-shared";

export type DentalDraftLineInput = {
  code: string | null; description: string | null; editionYear: number | null; serviceDate: string | null;
  quantity: number; /** Extended charge, already includes quantity. Null means unknown. */
  chargeCents: number | null; chargeReference: string | null; teeth: string[]; surfaces: string[];
  oralCavity: string | null; prosthesisNotes: string | null;
};
export type DentalDraftContentInput = {
  renderingProviderId: string; billingProviderId?: string | null; diagnosisCodes: string[];
  notes: string | null; lines: DentalDraftLineInput[];
};
export type DentalDraftEditorProps = TreatmentDraftAppearance & {
  /** Use a different React key when switching drafts; edits remain local until Save. */
  initialContent: DentalDraftContentInput;
  /** Host persists content using the public dental-drafts API and handles revision conflicts. Never transmits a claim. */
  onSave: (content: DentalDraftContentInput) => Promise<void>;
};
export function dentalDraftChargeSummary(lines: readonly Pick<DentalDraftLineInput, "chargeCents">[]) {
  const knownChargeCents = lines.reduce((sum, line) => sum + (line.chargeCents ?? 0), 0);
  return { knownChargeCents, totalChargeCents: lines.some((line) => line.chargeCents === null) ? null : knownChargeCents };
}
/** Convert decimal dollars exactly; reject excess precision, zero, and exponential notation. */
export function parseDentalCharge(value: string): number | null {
  if (!value.trim()) return null;
  if (!/^\d+(?:\.\d{1,2})?$/.test(value)) throw new Error("Enter a positive charge with at most two decimal places, or leave it blank.");
  const [whole = "0", fraction = ""] = value.split(".");
  const cents = Number(whole) * 100 + Number(fraction.padEnd(2, "0"));
  if (!Number.isSafeInteger(cents) || cents < 1 || cents > 1_000_000_000) throw new Error("Enter a charge between $0.01 and $10,000,000, or leave it blank.");
  return cents;
}
export function validateDentalDraftContent(content: DentalDraftContentInput): string | null {
  if (!content.renderingProviderId.trim() || content.renderingProviderId.length > 255) return "Choose a rendering provider in the host application.";
  if (content.billingProviderId != null && (!content.billingProviderId.trim() || content.billingProviderId.length > 255)) return "Choose a valid billing provider in the host application.";
  if (content.lines.length > 100) return "A draft can contain up to 100 service lines.";
  if (content.diagnosisCodes.length > 12 || content.diagnosisCodes.some((code) => !code.trim() || code.length > 20)) return "Enter up to 12 diagnosis codes of at most 20 characters each.";
  if (content.notes !== null && (!content.notes.trim() || content.notes.length > 5000)) return "Notes must contain between 1 and 5,000 characters.";
  for (const [index, line] of content.lines.entries()) {
    const prefix = `Line ${index + 1}: `;
    if (line.code !== null && !/^D[0-9]{4}$/.test(line.code)) return prefix + "enter D followed by four digits, or leave the code blank.";
    if (!Number.isInteger(line.quantity) || line.quantity < 1 || line.quantity > 100000) return prefix + "enter a whole quantity between 1 and 100,000.";
    if (line.chargeCents !== null && (!Number.isSafeInteger(line.chargeCents) || line.chargeCents < 1 || line.chargeCents > 1_000_000_000)) return prefix + "enter a positive extended charge, or leave it unknown.";
    if (line.serviceDate !== null && !isDraftDate(line.serviceDate)) return prefix + "enter a valid service date.";
    if (line.editionYear !== null && (!Number.isInteger(line.editionYear) || line.editionYear < 1900 || line.editionYear > 2200)) return prefix + "enter an edition year between 1900 and 2200.";
    for (const [value, limit] of [[line.description, 1000], [line.chargeReference, 1000], [line.oralCavity, 100], [line.prosthesisNotes, 2000]] as const) {
      if (value !== null && (!value.trim() || value.length > limit)) return prefix + `text must contain between 1 and ${limit} characters.`;
    }
    if (line.teeth.length > 32 || line.surfaces.length > 10 || [...line.teeth, ...line.surfaces].some((value) => !value.trim() || value.length > 20)) return prefix + "check tooth and surface entries (up to 32 teeth and 10 surfaces, 20 characters each).";
  }
  return null;
}
const blankLine = (): DentalDraftLineInput => ({ code: null, description: null, editionYear: null, serviceDate: null, quantity: 1, chargeCents: null, chargeReference: null, teeth: [], surfaces: [], oralCavity: null, prosthesisNotes: null });
const nullable = (value: string) => value === "" ? null : value;
const split = (value: string) => value.split(",").map((part) => part.trim()).filter(Boolean);
const currency = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);

export function DentalDraftEditor({ initialContent, onSave, disabled = false, ...appearance }: DentalDraftEditorProps): ReactElement {
  const [content, setContent] = useState<DentalDraftContentInput>(() => structuredClone(initialContent));
  const [charges, setCharges] = useState(() => initialContent.lines.map((line) => line.chargeCents === null ? "" : (line.chargeCents / 100).toFixed(2)));
  const [diagnoses, setDiagnoses] = useState(() => initialContent.diagnosisCodes.join(", "));
  const [teeth, setTeeth] = useState(() => initialContent.lines.map((line) => line.teeth.join(", ")));
  const [surfaces, setSurfaces] = useState(() => initialContent.lines.map((line) => line.surfaces.join(", ")));
  const action = useDraftSave(onSave);
  const locked = disabled || action.busy;
  const updateLine = (index: number, patch: Partial<DentalDraftLineInput>) => { action.clear(); setContent((current) => ({ ...current, lines: current.lines.map((line, position) => position === index ? { ...line, ...patch } : line) })); };
  const parsed = () => ({ ...content, diagnosisCodes: split(diagnoses), lines: content.lines.map((line, index) => ({ ...line, teeth: split(teeth[index] ?? ""), surfaces: split(surfaces[index] ?? ""), chargeCents: parseDentalCharge(charges[index] ?? "") })) });
  let summary: ReturnType<typeof dentalDraftChargeSummary> | null = null;
  try { summary = dentalDraftChargeSummary(parsed().lines); } catch { /* Keep invalid text editable without showing a misleading total. */ }
  return <TreatmentDraftShell {...appearance} title="Dental draft" description="Record dental services, tooth details, and practice charges for review.">
    <p className="mbtd-note">Codes and prices need review. Saving does not send a dental claim. A blank charge remains unknown.</p>
    <form onSubmit={(event) => { event.preventDefault(); if (locked) return; let next: DentalDraftContentInput; try { next = parsed(); } catch { void action.save(content, "Enter positive charges with at most two decimal places, or leave them blank."); return; } void action.save(next, validateDentalDraftContent(next)); }}>
      <fieldset disabled={locked}><legend>Claim details</legend><div className="mbtd-grid"><label>Diagnosis codes, comma separated<input value={diagnoses} onChange={(event) => { action.clear(); setDiagnoses(event.target.value); }} /></label><label>Notes<textarea maxLength={5000} value={content.notes ?? ""} onChange={(event) => { action.clear(); setContent({ ...content, notes: nullable(event.target.value) }); }} /></label></div></fieldset>
      {content.lines.map((line, index) => <fieldset key={index} disabled={locked}><legend>Service {index + 1}</legend><div className="mbtd-grid">
        <label>Dental code<input placeholder="D0120" maxLength={5} value={line.code ?? ""} onChange={(event) => updateLine(index, { code: nullable(event.target.value.toUpperCase()) })} /></label>
        <label>Code edition year<input type="number" min={1900} max={2200} value={line.editionYear ?? ""} onChange={(event) => updateLine(index, { editionYear: event.target.value === "" ? null : Number(event.target.value) })} /></label>
        <label>Date of service<input type="date" value={line.serviceDate ?? ""} onChange={(event) => updateLine(index, { serviceDate: nullable(event.target.value) })} /></label>
        <label>Quantity<input type="number" min={1} max={100000} step={1} value={line.quantity} onChange={(event) => updateLine(index, { quantity: Number(event.target.value) })} /></label>
        <label>Extended line charge ($)<input inputMode="decimal" placeholder="Unknown" value={charges[index] ?? ""} onChange={(event) => { action.clear(); setCharges(charges.map((value, position) => position === index ? event.target.value : value)); }} /><small>Includes all units. This is the practice charge, not a fee allowance.</small></label>
        <label>Charge source / reference<input maxLength={1000} value={line.chargeReference ?? ""} onChange={(event) => updateLine(index, { chargeReference: nullable(event.target.value) })} /></label>
        <label>Teeth, comma separated<input value={teeth[index] ?? ""} onChange={(event) => { action.clear(); setTeeth(teeth.map((value, position) => position === index ? event.target.value : value)); }} /></label>
        <label>Surfaces, comma separated<input value={surfaces[index] ?? ""} onChange={(event) => { action.clear(); setSurfaces(surfaces.map((value, position) => position === index ? event.target.value.toUpperCase() : value)); }} /></label>
        <label>Oral cavity<input maxLength={100} value={line.oralCavity ?? ""} onChange={(event) => updateLine(index, { oralCavity: nullable(event.target.value) })} /></label>
        <label>Service description<input maxLength={1000} value={line.description ?? ""} onChange={(event) => updateLine(index, { description: nullable(event.target.value) })} /></label>
        <label className="mbtd-wide">Prosthesis notes<textarea maxLength={2000} value={line.prosthesisNotes ?? ""} onChange={(event) => updateLine(index, { prosthesisNotes: nullable(event.target.value) })} /></label>
      </div><div className="mbtd-actions"><button type="button" onClick={() => { action.clear(); setContent({ ...content, lines: content.lines.filter((_, position) => position !== index) }); setCharges(charges.filter((_, position) => position !== index)); setTeeth(teeth.filter((_, position) => position !== index)); setSurfaces(surfaces.filter((_, position) => position !== index)); }}>Remove service {index + 1}</button></div></fieldset>)}
      <div><button type="button" disabled={locked || content.lines.length >= 100} onClick={() => { action.clear(); setContent({ ...content, lines: [...content.lines, blankLine()] }); setCharges([...charges, ""]); setTeeth([...teeth, ""]); setSurfaces([...surfaces, ""]); }}>Add dental service</button></div>
      <p role="status">{summary ? summary.totalChargeCents === null ? `Known charges: ${currency(summary.knownChargeCents)} · Total incomplete` : `Total practice charge: ${currency(summary.totalChargeCents)}` : "Review charge amounts before saving."}</p>
      {action.error ? <p role="alert">{action.error}</p> : null}<div className="mbtd-actions"><button type="submit" className="mbtd-primary" disabled={locked}>{action.busy ? "Saving…" : "Save dental draft"}</button><p role="status">{action.message}</p></div>
    </form>
  </TreatmentDraftShell>;
}
