// packages/react/src/connected-billing-workspace.tsx
"use client";

import {
  useCallback,
  useEffect,
  useMemo,
  useState,
  type CSSProperties,
  type ReactElement,
  type ReactNode,
} from "react";
import type { BillTasksDashboardCell } from "./bill-tasks-dashboard";
import { BillTasksDashboard } from "./bill-tasks-dashboard";
import { ConnectedBillLifecycle } from "./connected-bill-lifecycle";
import { mindBillAppearanceStyle, type MindBillReactAppearance } from "./appearance";
import {
  createBillingOperationsClient,
  type BillingOperationsClientOptions,
  type BillRegistryAge,
  type BillRegistryItem,
  type BillRegistryQuery,
  type BillRegistryResult,
  type BillTasksResult,
  type ProductivityReport,
  type ServiceLineItemsReport,
} from "./billing-operations-client";

type ConnectedSurfaceProps = BillingOperationsClientOptions & {
  appearance?: MindBillReactAppearance;
  className?: string;
  style?: CSSProperties;
};

const css = `
.mbow{color:var(--mb-text);font:14px/1.45 var(--mb-font);background:var(--mb-soft);border-radius:var(--mb-radius);padding:20px}.mbow *{box-sizing:border-box}.mbow h2,.mbow h3,.mbow p{margin:0}.mbow a{color:var(--mb-accent)}
.mbow-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:18px}.mbow-head h2{font-size:24px;line-height:1.2}.mbow-sub{color:var(--mb-muted);margin-top:4px!important}.mbow-actions{display:flex;gap:8px;flex-wrap:wrap}
.mbow-button,.mbow-input,.mbow-select{min-height:38px;border:1px solid var(--mb-border);border-radius:var(--mb-control-radius);background:var(--mb-input);color:var(--mb-text);font:inherit}.mbow-button{padding:7px 12px;cursor:pointer;font-weight:650}.mbow-button:hover{border-color:var(--mb-accent)}.mbow-button.primary{background:var(--mb-accent);border-color:var(--mb-accent);color:var(--mb-accent-contrast)}.mbow-button:disabled{opacity:.55;cursor:not-allowed}.mbow-input,.mbow-select{padding:7px 10px}.mbow-input{min-width:260px;flex:1}
.mbow-tabs{display:flex;gap:4px;border-bottom:1px solid var(--mb-border);margin-bottom:18px;overflow:auto}.mbow-tab{border:0;border-bottom:3px solid transparent;background:transparent;color:var(--mb-muted);padding:10px 13px;font:inherit;font-weight:700;white-space:nowrap;cursor:pointer}.mbow-tab.active{color:var(--mb-text);border-bottom-color:var(--mb-accent)}
.mbow-toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:14px}.mbow-card{background:var(--mb-surface);border:1px solid var(--mb-border);border-radius:var(--mb-radius);box-shadow:var(--mb-shadow);overflow:hidden}.mbow-scroll{overflow:auto}.mbow-table{width:100%;border-collapse:collapse;min-width:820px}.mbow-table th,.mbow-table td{padding:11px 12px;border-bottom:1px solid var(--mb-border);text-align:left;vertical-align:middle}.mbow-table th{color:var(--mb-muted);font-size:11px;letter-spacing:.045em;text-transform:uppercase;font-weight:800;background:color-mix(in srgb,var(--mb-soft) 60%,var(--mb-surface))}.mbow-table tr:last-child td{border-bottom:0}.mbow-table tbody tr.clickable{cursor:pointer}.mbow-table tbody tr.clickable:hover{background:color-mix(in srgb,var(--mb-accent) 6%,var(--mb-surface))}.mbow-money{text-align:right!important;font-variant-numeric:tabular-nums}.mbow-strong{font-weight:760}.mbow-muted{color:var(--mb-muted);font-size:12px}.mbow-badge{display:inline-flex;border:1px solid var(--mb-border);border-radius:999px;padding:2px 8px;font-size:12px;background:var(--mb-soft);white-space:nowrap}.mbow-badge.success{color:var(--mb-success);border-color:color-mix(in srgb,var(--mb-success) 35%,var(--mb-border));background:color-mix(in srgb,var(--mb-success) 8%,var(--mb-surface))}.mbow-badge.danger{color:var(--mb-danger)}.mbow-badge.warning{color:var(--mb-warning)}
.mbow-state{padding:28px;text-align:center;color:var(--mb-muted)}.mbow-error{color:var(--mb-danger)}.mbow-pager{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px;color:var(--mb-muted)}
.mbow-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:14px 0 18px}.mbow-metric{padding:16px;background:var(--mb-surface);border:1px solid var(--mb-border);border-radius:var(--mb-radius);box-shadow:var(--mb-shadow)}.mbow-metric span{display:block;color:var(--mb-muted);font-size:11px;text-transform:uppercase;letter-spacing:.05em}.mbow-metric strong{display:block;font-size:24px;margin-top:5px}.mbow-section-head{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:14px 16px;border-bottom:1px solid var(--mb-border)}
.mbow-back{margin-bottom:12px}.mbow-task-note{color:var(--mb-muted);font-size:13px;margin-bottom:14px!important}.mbow-bar{height:7px;min-width:70px;background:var(--mb-soft);border-radius:99px;overflow:hidden}.mbow-bar i{display:block;height:100%;background:var(--mb-accent);border-radius:inherit}
@media(max-width:760px){.mbow{padding:14px}.mbow-head{display:block}.mbow-actions{margin-top:12px}.mbow-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.mbow-input{min-width:100%}}
`;

function money(value: number): string {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);
}

function shortDate(value: string | null): string {
  if (!value) return "—";
  const date = new Date(`${value.slice(0, 10)}T12:00:00`);
  return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString("en-US");
}

function defaultRange(days = 29): { from: string; to: string } {
  const to = new Date();
  const from = new Date(to);
  from.setDate(to.getDate() - days);
  const iso = (date: Date) => date.toISOString().slice(0, 10);
  return { from: iso(from), to: iso(to) };
}

function Surface({ appearance, className = "", style, children }: {
  appearance?: MindBillReactAppearance | undefined;
  className?: string | undefined;
  style?: CSSProperties | undefined;
  children: ReactNode;
}): ReactElement {
  return <div className={`mbow ${className}`.trim()} style={mindBillAppearanceStyle(appearance, style)}><style>{css}</style>{children}</div>;
}

function useClient(options: BillingOperationsClientOptions) {
  return useMemo(() => createBillingOperationsClient(options), [options.apiBaseUrl, options.fetch, options.getSession, options.sessionEndpoint]);
}

export type ConnectedBillSearchProps = ConnectedSurfaceProps & {
  initialQuery?: BillRegistryQuery;
  onSelectBill?: (bill: BillRegistryItem) => void;
  heading?: ReactNode;
  compact?: boolean;
};

function BillSearchContent({
  client,
  initialQuery,
  onSelectBill,
  heading,
}: {
  client: ReturnType<typeof createBillingOperationsClient>;
  initialQuery?: BillRegistryQuery | undefined;
  onSelectBill?: ((bill: BillRegistryItem) => void) | undefined;
  heading?: ReactNode | undefined;
}): ReactElement {
  const [query, setQuery] = useState<BillRegistryQuery>({ status: "all", age: "all", page: 1, pageSize: 25, sort: "submitted_desc", ...initialQuery });
  const [draft, setDraft] = useState(initialQuery?.q ?? "");
  const [result, setResult] = useState<BillRegistryResult | null>(null);
  const [error, setError] = useState<Error | null>(null);
  const [loading, setLoading] = useState(true);
  const load = useCallback(async (signal?: AbortSignal) => {
    setLoading(true); setError(null);
    try { setResult(await client.getBills(query, signal)); }
    catch (cause) { if (!signal?.aborted) setError(cause instanceof Error ? cause : new Error("Bills could not be loaded.")); }
    finally { if (!signal?.aborted) setLoading(false); }
  }, [client, query]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  const update = (next: Partial<BillRegistryQuery>) => setQuery((current) => ({ ...current, ...next, page: next.page ?? 1 }));
  const pageCount = Math.max(1, Math.ceil((result?.total ?? 0) / (result?.pageSize ?? 25)));

  return <>
    {heading ? <div className="mbow-head"><div>{typeof heading === "string" ? <h2>{heading}</h2> : heading}</div></div> : null}
    <form className="mbow-toolbar" onSubmit={(event) => { event.preventDefault(); update({ q: draft.trim() }); }}>
      <input className="mbow-input" value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Search patient, bill ID, claim, or external ID…" aria-label="Search bills" />
      <select className="mbow-select" value={query.status ?? "all"} onChange={(event) => update({ status: event.target.value })} aria-label="Bill status">
        <option value="all">All statuses</option><option value="incomplete">Incomplete</option><option value="submitted">Submitted</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option><option value="processed">Processed</option><option value="paid">Paid</option><option value="closed">Closed</option>
      </select>
      <select className="mbow-select" value={query.age ?? "all"} onChange={(event) => update({ age: event.target.value as BillRegistryAge })} aria-label="A/R age">
        <option value="all">All A/R ages</option><option value="0-30">0–30 days</option><option value="31-60">31–60 days</option><option value="61-90">61–90 days</option><option value="91+">91+ days</option><option value="91-180">91–180 days</option><option value="181+">181+ days</option>
      </select>
      <button className="mbow-button" type="submit">Search</button>
    </form>
    <div className="mbow-card mbow-scroll">
      {loading && !result ? <div className="mbow-state" role="status">Loading bills…</div> : error && !result ? <div className="mbow-state mbow-error" role="alert">{error.message} <button className="mbow-button" type="button" onClick={() => void load()}>Retry</button></div> : result?.items.length === 0 ? <div className="mbow-state">No bills match these filters.</div> : <table className="mbow-table">
        <thead><tr><th>Bill</th><th>Patient</th><th>DOS</th><th>Codes</th><th>Claims administrator</th><th>Status</th><th>Submitted / A/R age</th><th className="mbow-money">Balance due</th></tr></thead>
        <tbody>{result?.items.map((bill) => <tr key={bill.id} className={onSelectBill ? "clickable" : ""} onClick={() => onSelectBill?.(bill)}>
          <td className="mbow-strong">#{bill.billNumber}</td><td>{bill.patientName}</td><td>{shortDate(bill.dateOfService)}</td><td>{bill.procedureCodes.join(", ") || "—"}</td><td>{bill.claimsAdministrator || "—"}</td><td><span className={`mbow-badge ${bill.status.tone ?? ""}`}>{bill.status.label}</span></td><td>{shortDate(bill.submittedAt)}<div className="mbow-muted">{bill.arAgeDays == null ? "—" : `${bill.arAgeDays} days`}</div></td><td className="mbow-money mbow-strong">{money(bill.balanceDue)}</td>
        </tr>)}</tbody>
      </table>}
      {result ? <div className="mbow-pager"><span>Showing {result.total === 0 ? 0 : (result.page - 1) * result.pageSize + 1}–{Math.min(result.page * result.pageSize, result.total)} of {result.total}</span><span><button className="mbow-button" type="button" disabled={result.page <= 1} onClick={() => update({ page: result.page - 1 })}>Previous</button> {result.page} / {pageCount} <button className="mbow-button" type="button" disabled={result.page >= pageCount} onClick={() => update({ page: result.page + 1 })}>Next</button></span></div> : null}
    </div>
  </>;
}

export function ConnectedBillSearch({ appearance, className, style, initialQuery, onSelectBill, heading = "All bills", ...options }: ConnectedBillSearchProps): ReactElement {
  const client = useClient(options);
  return <Surface appearance={appearance} className={className} style={style}><BillSearchContent client={client} initialQuery={initialQuery} onSelectBill={onSelectBill} heading={heading} /></Surface>;
}

export type ConnectedBillTasksDashboardProps = ConnectedSurfaceProps & {
  onDrillDown?: (query: BillRegistryQuery) => void;
};

function taskQuery(cell: BillTasksDashboardCell): BillRegistryQuery {
  const [taskType, taskLabel] = cell.rowId.split("::", 2);
  const age = cell.bucketId === "1-30" ? "0-30" : cell.bucketId as BillRegistryAge | null;
  return { status: "all", taskSection: cell.sectionId, ...(taskType ? { taskType } : {}), ...(taskLabel ? { taskLabel } : {}), ...(age ? { age } : {}) };
}

function BillTasksContent({ client, onDrillDown, appearance }: { client: ReturnType<typeof createBillingOperationsClient>; onDrillDown?: ((query: BillRegistryQuery) => void) | undefined; appearance?: MindBillReactAppearance | undefined }): ReactElement {
  const [claimsAdminId, setClaimsAdminId] = useState("");
  const [result, setResult] = useState<BillTasksResult | null>(null);
  const [error, setError] = useState<Error | null>(null);
  const [loading, setLoading] = useState(true);
  const load = useCallback(async (signal?: AbortSignal) => { setLoading(true); setError(null); try { setResult(await client.getBillTasks(claimsAdminId || undefined, signal)); } catch (cause) { if (!signal?.aborted) setError(cause instanceof Error ? cause : new Error("Bill tasks could not be loaded.")); } finally { if (!signal?.aborted) setLoading(false); } }, [claimsAdminId, client]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  if (loading && !result) return <div className="mbow-state">Loading bill tasks…</div>;
  if (error && !result) return <div className="mbow-state mbow-error">{error.message}</div>;
  if (!result) return <></>;
  return <>
    <p className="mbow-task-note">Open follow-up work only. Sent bills waiting on a payer stay available in <strong>All bills</strong>.</p>
    <BillTasksDashboard data={result.dashboard} appearance={appearance ?? { preset: "mindbill" }} toolbar={<select className="mbow-select" value={claimsAdminId} onChange={(event) => setClaimsAdminId(event.target.value)}><option value="">All claims administrators</option>{result.filters.claimsAdministrators.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>} onSelectCell={(cell) => onDrillDown?.(taskQuery(cell))} />
  </>;
}

export function ConnectedBillTasksDashboard({ appearance, className, style, onDrillDown, ...options }: ConnectedBillTasksDashboardProps): ReactElement {
  const client = useClient(options);
  return <Surface appearance={appearance} className={className} style={style}><BillTasksContent client={client} onDrillDown={onDrillDown} appearance={appearance} /></Surface>;
}

type ReportProps = ConnectedSurfaceProps & { initialFrom?: string; initialTo?: string; onSelectBill?: (billId: string) => void };

function RangeToolbar({ from, to, setFrom, setTo }: { from: string; to: string; setFrom: (value: string) => void; setTo: (value: string) => void }): ReactElement {
  return <div className="mbow-toolbar"><label>From <input className="mbow-input" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>To <input className="mbow-input" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label></div>;
}

export function ConnectedServiceLineItemsReport({ appearance, className, style, initialFrom, initialTo, onSelectBill, ...options }: ReportProps): ReactElement {
  const defaults = useMemo(() => defaultRange(), []); const client = useClient(options);
  const [from, setFrom] = useState(initialFrom ?? defaults.from); const [to, setTo] = useState(initialTo ?? defaults.to); const [data, setData] = useState<ServiceLineItemsReport | null>(null); const [error, setError] = useState<Error | null>(null);
  useEffect(() => { const controller = new AbortController(); setError(null); void client.getServiceLineItems({ from, to }, controller.signal).then(setData).catch((cause) => { if (!controller.signal.aborted) setError(cause instanceof Error ? cause : new Error("Report could not be loaded.")); }); return () => controller.abort(); }, [client, from, to]);
  return <Surface appearance={appearance} className={className} style={style}><div className="mbow-head"><div><h2>Original submissions by procedure</h2><p className="mbow-sub">First payer submission for each patient and date of service.</p></div></div><RangeToolbar from={from} to={to} setFrom={setFrom} setTo={setTo} />{error ? <div className="mbow-state mbow-error">{error.message}</div> : !data ? <div className="mbow-state">Loading report…</div> : <><div className="mbow-metrics"><Metric label="Original bills" value={String(data.totalBills)} /><Metric label="Service lines" value={String(data.totalLines)} /><Metric label="Total billed" value={money(data.totalBilled)} /><Metric label="Report window" value={data.windowLabel} /></div><div className="mbow-card mbow-scroll"><div className="mbow-section-head"><h3>Procedure summary</h3></div><table className="mbow-table"><thead><tr><th>Procedure code</th><th>Bills</th><th>Service lines</th><th className="mbow-money">Total billed</th></tr></thead><tbody>{data.cptRows.map((row) => <tr key={row.code}><td className="mbow-strong">{row.code}</td><td>{row.bills}</td><td>{row.lines}</td><td className="mbow-money">{money(row.billed)}</td></tr>)}</tbody></table></div><div className="mbow-card mbow-scroll" style={{ marginTop: 16 }}><div className="mbow-section-head"><h3>All original bills</h3></div><table className="mbow-table"><thead><tr><th>Bill</th><th>First submitted</th><th>Patient · Claim</th><th>DOS</th><th>Claims administrator</th><th>Codes</th><th className="mbow-money">Billed</th><th>Status</th></tr></thead><tbody>{data.billRows.map((row) => <tr key={row.billId} className={onSelectBill ? "clickable" : ""} onClick={() => onSelectBill?.(row.billId)}><td className="mbow-strong">#{row.billNumber}</td><td>{shortDate(row.submittedDate)}</td><td>{row.patient}<div className="mbow-muted">{row.claim}</div></td><td>{shortDate(row.dos)}</td><td>{row.claimsAdmin}</td><td>{row.codes.join(", ")}</td><td className="mbow-money">{money(row.billed)}</td><td>{row.status}</td></tr>)}</tbody></table></div></>}</Surface>;
}

function Metric({ label, value }: { label: string; value: string }): ReactElement { return <div className="mbow-metric"><span>{label}</span><strong>{value}</strong></div>; }

export function ConnectedProductivityReport({ appearance, className, style, initialFrom, initialTo, ...options }: Omit<ReportProps, "onSelectBill">): ReactElement {
  const defaults = useMemo(() => defaultRange(13), []); const client = useClient(options);
  const [from, setFrom] = useState(initialFrom ?? defaults.from); const [to, setTo] = useState(initialTo ?? defaults.to); const [data, setData] = useState<ProductivityReport | null>(null); const [error, setError] = useState<Error | null>(null);
  useEffect(() => { const controller = new AbortController(); setError(null); void client.getProductivity({ from, to }, controller.signal).then(setData).catch((cause) => { if (!controller.signal.aborted) setError(cause instanceof Error ? cause : new Error("Report could not be loaded.")); }); return () => controller.abort(); }, [client, from, to]);
  const maxSent = data ? Math.max(1, ...Object.values(data.sentTotal)) : 1;
  return <Surface appearance={appearance} className={className} style={style}><div className="mbow-head"><div><h2>Productivity</h2><p className="mbow-sub">Bills created and sent per biller, plus accepted-first-try rate.</p></div></div><RangeToolbar from={from} to={to} setFrom={setFrom} setTo={setTo} />{error ? <div className="mbow-state mbow-error">{error.message}</div> : !data ? <div className="mbow-state">Loading report…</div> : <><div className="mbow-metrics"><Metric label="Bills created" value={String(data.totalCreated)} /><Metric label="Transmissions" value={String(data.totalSent)} /><Metric label="Bills submitted" value={String(data.totalSubmitted)} /><Metric label="Accepted first try" value={data.totalSubmitted ? `${Math.round(data.totalClean / data.totalSubmitted * 100)}%` : "—"} /></div><div className="mbow-card mbow-scroll"><div className="mbow-section-head"><h3>Per-biller summary</h3></div><table className="mbow-table"><thead><tr><th>Biller</th><th>Created</th><th>Transmissions</th><th>Submitted</th><th>Accepted first try</th><th>Volume</th></tr></thead><tbody>{data.billers.map((biller) => { const sent = data.sentTotal[biller.name] ?? 0; const submitted = data.submittedTotal[biller.name] ?? 0; const clean = data.cleanTotal[biller.name] ?? 0; return <tr key={biller.name}><td className="mbow-strong">{biller.name}</td><td>{data.createdTotal[biller.name] ?? 0}</td><td>{sent}</td><td>{submitted}</td><td>{submitted ? `${Math.round(clean / submitted * 100)}%` : "—"}</td><td><div className="mbow-bar"><i style={{ width: `${sent / maxSent * 100}%` }} /></div></td></tr>; })}</tbody></table></div></>}</Surface>;
}

export type ConnectedBillingWorkspaceProps = ConnectedSurfaceProps & {
  initialView?: "tasks" | "bills" | "procedures" | "productivity";
  onCreateBill?: () => void;
};

export function ConnectedBillingWorkspace({ appearance, className, style, initialView = "tasks", onCreateBill, ...options }: ConnectedBillingWorkspaceProps): ReactElement {
  const client = useClient(options); const [view, setView] = useState(initialView); const [billQuery, setBillQuery] = useState<BillRegistryQuery>({ status: "all" }); const [selectedBillId, setSelectedBillId] = useState<string | null>(null);
  if (selectedBillId) return <Surface appearance={appearance} className={className} style={style}><button className="mbow-button mbow-back" type="button" onClick={() => setSelectedBillId(null)}>← Back to bills</button><ConnectedBillLifecycle billId={selectedBillId} {...options} {...(appearance ? { appearance } : {})} /></Surface>;
  const selectView = (next: typeof view) => { setView(next); setSelectedBillId(null); };
  const appearanceProps = appearance ? { appearance } : {};
  return <Surface appearance={appearance} className={className} style={style}><div className="mbow-head"><div><h2>Billing</h2><p className="mbow-sub">Follow up on open work or find any bill and its current status.</p></div>{onCreateBill ? <div className="mbow-actions"><button className="mbow-button primary" type="button" onClick={onCreateBill}>+ Add bill</button></div> : null}</div><div className="mbow-tabs" role="tablist">{([['tasks','Bill tasks'],['bills','All bills'],['procedures','Procedures'],['productivity','Productivity']] as const).map(([id,label]) => <button key={id} className={`mbow-tab ${view === id ? "active" : ""}`} type="button" role="tab" aria-selected={view === id} onClick={() => selectView(id)}>{label}</button>)}</div>{view === "tasks" ? <BillTasksContent client={client} onDrillDown={(query) => { setBillQuery(query); setView("bills"); }} appearance={appearance} /> : view === "bills" ? <BillSearchContent client={client} initialQuery={billQuery} onSelectBill={(bill) => setSelectedBillId(bill.id)} /> : view === "procedures" ? <ConnectedServiceLineItemsReport {...options} {...appearanceProps} onSelectBill={setSelectedBillId} /> : <ConnectedProductivityReport {...options} {...appearanceProps} />}</Surface>;
}

// packages/angular/src/lib/connected-billing-workspace.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, Directive, EventEmitter, inject, Input, Output, type OnChanges, type OnInit, type OnDestroy, type SimpleChanges } from '@angular/core';
import { createBillingOperationsClient, DEFAULT_API_BASE_URL, DEFAULT_SESSION_ENDPOINT, type BillingOperationsClient, type BillLifecycleSessionProvider, type BillRegistryQuery, type BillRegistryResult, type BillTasksResult, type PaymentReviewQuery, type PaymentReviewResult, type ServiceLineItemsReport, type ProductivityReport } from '@mindbill/browser';
import { mindBillAngularAppearanceStyle, type MindBillAngularAppearance } from './appearance';
import { MindBillBillTasksDashboardComponent } from './bill-tasks-dashboard.component';
import { type MindBillBillTasksCell } from './bill-tasks-dashboard';
import { MindBillBillLifecycleComponent } from './bill-lifecycle.component';
import { mindBillTaskQuery, mindBillPaymentDateRange, mindBillPaymentCsv, type MindBillBillingView, type MindBillPaymentRange } from './billing-operations';

const styles = `:host{display:block;min-width:0}.ops{font:14px/1.5 var(--font);color:var(--t);min-width:0}.ops *{box-sizing:border-box}h2,h3,p{margin:0}h2{font-size:22px}h3{font-size:16px}small,.muted{color:var(--m)}small{display:block}.head,.toolbar,.pager,.tabs{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.head,.pager{justify-content:space-between}.head,.toolbar{margin-bottom:16px}.tabs{border-bottom:1px solid var(--b);margin:18px 0;gap:4px}.tabs button{border:0;border-radius:0;border-bottom:3px solid transparent}.tabs button.active{border-color:var(--a);color:var(--a);background:transparent}button,input,select{font:inherit;color:var(--t);background:var(--s);border:1px solid var(--b);border-radius:var(--cr);padding:8px 10px;min-height:38px;max-width:100%}button{cursor:pointer}button:disabled{opacity:.5;cursor:default}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid var(--a);outline-offset:2px}.primary,button.active{background:var(--a);color:var(--ac)}label{display:grid;gap:4px;font-size:12px}.search{flex:1;min-width:180px}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px;margin:16px 0}.metric,.card{border:1px solid var(--b);border-radius:var(--r);background:var(--s)}.metric{padding:16px}.metric strong{display:block;font-size:24px;font-variant-numeric:tabular-nums}.scroll{overflow:auto;max-width:100%}table{width:100%;min-width:700px;border-collapse:collapse;text-align:left}th,td{padding:12px;border-bottom:1px solid var(--b);vertical-align:top}th{color:var(--m);font-size:12px;background:var(--bg)}.money{text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums}.link{border:0;background:none;color:var(--a);padding:0;min-height:30px}.state{padding:32px;text-align:center;color:var(--m)}.error{color:var(--danger)}.pager{padding:12px}.section-title{padding:14px}.stack{display:grid;gap:16px}.badge{border-radius:var(--cr);padding:3px 7px;background:var(--bg);white-space:nowrap}.bar{height:8px;background:var(--b);border-radius:4px;min-width:80px}.bar i{display:block;height:100%;background:var(--a);border-radius:4px}.footnote{margin-top:10px;font-size:12px;color:var(--m)}@media(max-width:600px){.tabs{flex-wrap:nowrap;overflow-x:auto}.tabs button{flex-shrink:0}.toolbar label{flex:1;min-width:130px}.search{min-width:100%}.metric{padding:10px}.metric strong{font-size:20px}}`;

@Directive()
export class MindBillOperationsBase implements OnChanges, OnInit, OnDestroy {
  @Input() sessionEndpoint = DEFAULT_SESSION_ENDPOINT;
  @Input() apiBaseUrl = DEFAULT_API_BASE_URL;
  @Input() getSession?: BillLifecycleSessionProvider;
  @Input() fetch?: typeof globalThis.fetch;
  @Input() appearance: MindBillAngularAppearance = { preset: 'mindbill' };
  @Input() initialQuery: BillRegistryQuery & PaymentReviewQuery = {};
  @Input() initialFrom = '';
  @Input() initialTo = '';
  @Input() view: MindBillBillingView = 'bills';
  @Input() showPostPayment = false;
  @Output() billSelected = new EventEmitter<string>();
  @Output() drillDown = new EventEmitter<BillRegistryQuery>();
  @Output() postPayment = new EventEmitter<void>();
  @Output() billingError = new EventEmitter<Error>();
  private readonly cdr = inject(ChangeDetectorRef);
  private client?: BillingOperationsClient;
  private controller?: AbortController;
  private initialized = false;
  loading = false; error = ''; search = ''; claimsAdminId = ''; renderingProviderId = '';
  query: BillRegistryQuery = { status:'all',age:'all',page:1,pageSize:25,sort:'submitted_desc' };
  paymentQuery: PaymentReviewQuery = { ...mindBillPaymentDateRange('month'),page:1,pageSize:25 };
  range: MindBillPaymentRange | null = 'month';
  from = ''; to = '';
  bills: BillRegistryResult | null = null;
  tasks: BillTasksResult | null = null;
  procedures: ServiceLineItemsReport | null = null;
  productivity: ProductivityReport | null = null;
  payments: PaymentReviewResult | null = null;
  statuses = [['all','All statuses'],['incomplete','Incomplete'],['sent','Sent'],['accepted','Accepted'],['accepted_no_response','Accepted · no response'],['rejected','Rejected'],['processed','Processed'],['paid','Paid'],['closed','Closed']];
  ages = ['all','0-30','31-60','61-90','91+','91-180','181+'];
  ranges: Array<{id:MindBillPaymentRange;label:string}> = [{id:'today',label:'Today'},{id:'week',label:'This week'},{id:'month',label:'This month'},{id:'year',label:'This year'},{id:'all',label:'All dates'}];
  get themeStyle(): Record<string,string> { return mindBillAngularAppearanceStyle(this.appearance); }
  value(event: Event): string { return (event.target as HTMLInputElement).value; }
  money(value: number): string { return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value); }
  paymentKey(billId: string, id: string): string { return JSON.stringify([billId,id]); }
  date(value: string | null): string { return value?.slice(0,10) || '—'; }
  percent(clean: number, total: number): string { return total ? `${Math.round(clean/total*100)}%` : '—'; }
  get maxSent(): number { return Math.max(1,...Object.values(this.productivity?.sentTotal ?? {})); }
  get pageResult(): {page:number;pageSize:number;total:number} | null { return this.view === 'payments' ? this.payments : this.bills; }
  get pageCount(): number { return Math.max(1,Math.ceil((this.pageResult?.total ?? 0)/(this.pageResult?.pageSize || 25))); }
  get invalidRange(): boolean { return this.view === 'payments' ? Boolean(this.paymentQuery.receivedFrom && this.paymentQuery.receivedTo && this.paymentQuery.receivedFrom > this.paymentQuery.receivedTo) : Boolean(this.from && this.to && this.from > this.to); }
  ngOnInit(): void { if (!this.initialized) this.ngOnChanges({}); }
  ngOnChanges(changes: SimpleChanges): void {
    const firstLoad = !this.initialized;
    if (!this.initialized || changes['initialQuery']) {
      this.query = {status:'all',age:'all',page:1,pageSize:25,sort:'submitted_desc',...this.initialQuery};
      this.paymentQuery = {...mindBillPaymentDateRange('month'),page:1,pageSize:25,...this.initialQuery};
      this.range = this.initialQuery.receivedFrom || this.initialQuery.receivedTo ? null : 'month';
      this.search = this.initialQuery.q ?? '';
    }
    if (!this.initialized || changes['initialFrom'] || changes['initialTo'] || changes['view']) {
      const now = new Date(); const start = new Date(now); start.setDate(start.getDate()-(this.view === 'productivity' ? 13 : 29));
      this.from = this.initialFrom || start.toISOString().slice(0,10); this.to = this.initialTo || now.toISOString().slice(0,10);
    }
    if (!this.client || changes['sessionEndpoint'] || changes['apiBaseUrl'] || changes['getSession'] || changes['fetch']) this.client = createBillingOperationsClient({sessionEndpoint:this.sessionEndpoint,apiBaseUrl:this.apiBaseUrl,...(this.getSession ? {getSession:this.getSession}:{}),...(this.fetch ? {fetch:this.fetch}:{})});
    this.initialized = true;
    if (changes['view']) this.search = (this.view === 'payments' ? this.paymentQuery.q : this.query.q) ?? '';
    if (firstLoad || Object.keys(changes).some(key => key !== 'appearance' && key !== 'showPostPayment')) void this.load();
  }
  ngOnDestroy(): void { this.controller?.abort(); }
  async load(): Promise<void> {
    this.controller?.abort(); const controller = new AbortController(); this.controller = controller;
    this.error = ''; this.bills = null; this.tasks = null; this.procedures = null; this.productivity = null; this.payments = null;
    if (this.invalidRange && this.view !== 'bills' && this.view !== 'tasks') { this.loading = false; this.cdr.markForCheck(); return; }
    this.loading = true;
    try {
      const client = this.client ??= createBillingOperationsClient({sessionEndpoint:this.sessionEndpoint,apiBaseUrl:this.apiBaseUrl,...(this.getSession ? {getSession:this.getSession}:{}),...(this.fetch ? {fetch:this.fetch}:{})});
      const signal = controller.signal;
      const view = this.view;
      if (view === 'bills') { const result = await client.getBills(this.query,signal); if (!signal.aborted) this.bills = result; }
      if (view === 'tasks') { const result = await client.getBillTasks(this.claimsAdminId || undefined,signal,this.renderingProviderId || undefined); if (!signal.aborted) this.tasks = result; }
      if (view === 'procedures') { const result = await client.getServiceLineItems({from:this.from,to:this.to},signal); if (!signal.aborted) this.procedures = result; }
      if (view === 'productivity') { const result = await client.getProductivity({from:this.from,to:this.to},signal); if (!signal.aborted) this.productivity = result; }
      if (view === 'payments') { const result = await client.getPaymentReview(this.paymentQuery,signal); if (!signal.aborted) this.payments = result; }
    } catch (cause) { if (!controller.signal.aborted) { const error = cause instanceof Error ? cause : new Error('Billing data could not be loaded.'); this.error = error.message; this.billingError.emit(error); } }
    finally { if (!controller.signal.aborted) { this.loading = false; this.cdr.markForCheck(); } }
  }
  update(field: string, value: string): void {
    if (this.view === 'payments') { this.paymentQuery = {...this.paymentQuery,[field]:value,page:1}; if (field.startsWith('received')) this.range = null; }
    else this.query = {...this.query,[field]:value,page:1};
    void this.load();
  }
  submitSearch(event: Event): void { event.preventDefault(); this.update('q',this.search); }
  changePage(offset: number): void { const page = Math.max(1,(this.pageResult?.page ?? 1)+offset); if (this.view === 'payments') this.paymentQuery = {...this.paymentQuery,page}; else this.query = {...this.query,page}; void this.load(); }
  setRange(range: MindBillPaymentRange): void { this.range = range; const next = {...this.paymentQuery}; delete next.receivedFrom; delete next.receivedTo; this.paymentQuery = {...next,...mindBillPaymentDateRange(range),page:1}; void this.load(); }
  taskSelected(cell: MindBillBillTasksCell): void { if (this.loading || this.error) return; this.drillDown.emit({...mindBillTaskQuery(cell),...(this.claimsAdminId ? {claimsAdministrator:this.claimsAdminId}:{}),...(this.renderingProviderId ? {renderingProviderId:this.renderingProviderId}:{})}); }
  exportPage(): void { if (!this.payments?.items.length || this.loading) return; const url = URL.createObjectURL(new Blob([mindBillPaymentCsv(this.payments.items)],{type:'text/csv;charset=utf-8'})); const a = document.createElement('a'); a.href=url; a.download='payment-review-page.csv'; a.click(); URL.revokeObjectURL(url); }
}

@Component({selector:'mindbill-connected-billing-panel',standalone:true,imports:[CommonModule,MindBillBillTasksDashboardComponent],templateUrl:'./connected-billing-panel.html',styles:[styles]})
export class MindBillConnectedBillingPanelComponent extends MindBillOperationsBase {}
@Component({selector:'mindbill-connected-bill-search',standalone:true,imports:[CommonModule,MindBillBillTasksDashboardComponent],templateUrl:'./connected-billing-panel.html',styles:[styles]})
export class MindBillConnectedBillSearchComponent extends MindBillOperationsBase { override view: MindBillBillingView = 'bills'; }
@Component({selector:'mindbill-connected-bill-tasks-dashboard',standalone:true,imports:[CommonModule,MindBillBillTasksDashboardComponent],templateUrl:'./connected-billing-panel.html',styles:[styles]})
export class MindBillConnectedBillTasksDashboardComponent extends MindBillOperationsBase { override view: MindBillBillingView = 'tasks'; }
@Component({selector:'mindbill-connected-service-line-items-report',standalone:true,imports:[CommonModule,MindBillBillTasksDashboardComponent],templateUrl:'./connected-billing-panel.html',styles:[styles]})
export class MindBillConnectedServiceLineItemsReportComponent extends MindBillOperationsBase { override view: MindBillBillingView = 'procedures'; }
@Component({selector:'mindbill-connected-productivity-report',standalone:true,imports:[CommonModule,MindBillBillTasksDashboardComponent],templateUrl:'./connected-billing-panel.html',styles:[styles]})
export class MindBillConnectedProductivityReportComponent extends MindBillOperationsBase { override view: MindBillBillingView = 'productivity'; }
@Component({selector:'mindbill-connected-payment-review',standalone:true,imports:[CommonModule,MindBillBillTasksDashboardComponent],templateUrl:'./connected-billing-panel.html',styles:[styles]})
export class MindBillConnectedPaymentReviewComponent extends MindBillOperationsBase { override view: MindBillBillingView = 'payments'; }

let workspaceCount = 0;

/** Session-authenticated operations workspace; create and payment entry remain host-owned actions. */
@Component({
  selector:'mindbill-connected-billing-workspace',standalone:true,
  imports:[CommonModule,MindBillConnectedBillingPanelComponent,MindBillBillLifecycleComponent],styles:[styles],
  template:`<section class="ops" [ngStyle]="themeStyle" aria-label="Billing workspace">
    @if (selectedBillId) {
      <div class="toolbar"><button type="button" (click)="selectedBillId=null">← Back to {{view === 'tasks' ? 'bill tasks' : view === 'bills' ? 'bills' : view === 'procedures' ? 'procedures' : view === 'payments' ? 'payment review' : 'productivity'}}</button></div>
      <mindbill-bill-lifecycle [billId]="selectedBillId" [sessionEndpoint]="sessionEndpoint" [apiBaseUrl]="apiBaseUrl" [getSession]="getSession" [appearance]="appearance" (billingError)="billingError.emit($event)" />
    } @else {
      <div class="head"><div><h2>Billing</h2><p class="muted">Follow up on open work or find any bill and its current status.</p></div>@if (showCreateBill) {<button type="button" class="primary" (click)="createBill.emit()">+ Add bill</button>}</div>
      <div class="tabs" role="tablist" aria-label="Billing views">@for (tab of tabs; track tab.id) {<button type="button" role="tab" [id]="workspaceId+'-tab-'+tab.id" [attr.aria-controls]="workspaceId+'-panel-'+tab.id" [attr.aria-selected]="view===tab.id" [attr.tabindex]="view===tab.id ? 0 : -1" [class.active]="view===tab.id" (click)="view=tab.id" (keydown)="tabKey($event,tab.id)">{{tab.label}}</button>}</div>
      <div role="tabpanel" [id]="workspaceId+'-panel-'+view" [attr.aria-labelledby]="workspaceId+'-tab-'+view">
        <mindbill-connected-billing-panel [view]="view" [sessionEndpoint]="sessionEndpoint" [apiBaseUrl]="apiBaseUrl" [getSession]="getSession" [fetch]="fetch" [appearance]="appearance" [initialQuery]="billQuery" [showPostPayment]="showPostPayment" (billSelected)="selectBill($event)" (drillDown)="openTasks($event)" (postPayment)="postPayment.emit()" (billingError)="billingError.emit($event)" />
      </div>
    }
  </section>`,
})
export class MindBillConnectedBillingWorkspaceComponent implements OnChanges {
  readonly workspaceId = `mindbill-workspace-${++workspaceCount}`;
  @Input() sessionEndpoint = DEFAULT_SESSION_ENDPOINT;
  @Input() apiBaseUrl = DEFAULT_API_BASE_URL;
  @Input() getSession?: BillLifecycleSessionProvider;
  @Input() fetch?: typeof globalThis.fetch;
  @Input() appearance: MindBillAngularAppearance = {preset:'mindbill'};
  @Input() initialView: MindBillBillingView = 'tasks';
  @Input() showCreateBill = false;
  @Input() showPostPayment = false;
  @Output() createBill = new EventEmitter<void>();
  @Output() postPayment = new EventEmitter<void>();
  @Output() billSelected = new EventEmitter<string>();
  @Output() billingError = new EventEmitter<Error>();
  view: MindBillBillingView = 'tasks';
  selectedBillId: string | null = null;
  billQuery: BillRegistryQuery = {status:'all'};
  tabs: Array<{id:MindBillBillingView;label:string}> = [{id:'tasks',label:'Bill tasks'},{id:'bills',label:'All bills'},{id:'procedures',label:'Procedures'},{id:'productivity',label:'Productivity'},{id:'payments',label:'Payment review'}];
  get themeStyle(): Record<string,string> { return mindBillAngularAppearanceStyle(this.appearance); }
  ngOnChanges(changes: SimpleChanges): void { if (changes['initialView']) this.view = this.initialView; }
  selectBill(id:string): void { this.selectedBillId=id; this.billSelected.emit(id); }
  openTasks(query:BillRegistryQuery): void { this.billQuery=query;this.view='bills'; }
  tabKey(event:KeyboardEvent,current:MindBillBillingView): void {
    const index=this.tabs.findIndex(tab=>tab.id===current); let next=index;
    if (event.key==='ArrowRight') next=(index+1)%this.tabs.length;
    else if (event.key==='ArrowLeft') next=(index+this.tabs.length-1)%this.tabs.length;
    else if (event.key==='Home') next=0;
    else if (event.key==='End') next=this.tabs.length-1;
    else return;
    event.preventDefault();this.view=this.tabs[next]!.id;
    const buttons=(event.currentTarget as HTMLElement).parentElement?.querySelectorAll<HTMLButtonElement>('[role="tab"]');buttons?.[next]?.focus();
  }
}
