// packages/react/src/rfa-authorization-destination.tsx
"use client";
import { useEffect, useRef, useState, type ReactElement } from "react";
import { normalizeRfaFax, rfaAuthorizationDestinations, rfaAuthorizationGuidance, type BillClaimsAdministratorDirectory, type RfaAuthorizationDestinationOption } from "@mindbill/browser";

export type RfaAuthorizationDestinationProps = {
  /** Change this when switching the RFA, claims administrator, or injury state. */
  contextKey: string;
  directory: BillClaimsAdministratorDirectory | null;
  loading?: boolean;
  error?: string | null;
  disabled?: boolean;
  /** Selection only: the host owns signing, destination confirmation, and delivery. */
  onChange: (destination: RfaAuthorizationDestinationOption | null) => void;
};

/** Choose a destination without sending an RFA or treating email as fax. */
export function RfaAuthorizationDestination({ contextKey, directory, loading = false, error, disabled = false, onChange }: RfaAuthorizationDestinationProps): ReactElement {
  const options = loading || error ? [] : rfaAuthorizationDestinations(directory);
  const signature = JSON.stringify([contextKey, directory?.authorizationStatus, options, loading, error]);
  const [selection, setSelection] = useState("");
  const [manual, setManual] = useState("");
  const callback = useRef(onChange);
  callback.current = onChange;
  useEffect(() => { setSelection(""); setManual(""); callback.current(null); }, [signature]);
  const chosen = options[Number(selection)];
  return <fieldset className="mb-rfa-destination" disabled={disabled || loading} style={{ border: "1px solid var(--mb-border, #d7e0df)", borderRadius: 10, padding: 16, display: "grid", gap: 12, minWidth: 0, overflowWrap: "anywhere" }}>
    <legend>Authorization destination</legend>
    <p style={{ margin: 0 }}>{loading ? "Loading authorization contacts…" : error ? "Directory details are unavailable. Confirm a destination with the handling adjuster." : rfaAuthorizationGuidance(directory)}</p>
    {directory?.authorizationNotice ? <p style={{ margin: 0 }}>{directory.authorizationNotice}</p> : null}
    {directory?.authorizationSource ? <small>Directory observed: {directory.authorizationSource.observedAt.slice(0, 10)}{ /^https?:\/\//i.test(directory.authorizationSource.url) ? <> · <a href={directory.authorizationSource.url} target="_blank" rel="noreferrer">Source</a></> : null}</small> : null}
    <label style={{ display: "grid", gap: 6, minWidth: 0 }}>{directory?.authorizationStatus === "claim_handling_location_routes" ? "Claim-handling office" : "Authorization contact"}
      <select value={selection} onChange={(event) => { const value = event.target.value; setSelection(value); setManual(""); onChange(value === "" || value === "manual" ? null : options[Number(value)] ?? null); }} style={{ padding: 10, width: "100%", minWidth: 0, maxWidth: "100%", font: "inherit" }}>
        <option value="">Choose a destination…</option>
        {options.map((option, index) => <option key={`${option.method}:${option.destination}:${index}`} value={String(index)}>{option.label} · {option.method === "fax" ? "Fax" : "Email"}: {option.destination}</option>)}
        <option value="manual">Enter a confirmed adjuster fax</option>
      </select>
    </label>
    {selection === "manual" ? <label style={{ display: "grid", gap: 6, minWidth: 0 }}>Authorization fax number<input type="tel" value={manual} onChange={(event) => { const value = event.target.value; setManual(value); const fax = normalizeRfaFax(value); onChange(fax ? { method: "fax", destination: fax, label: "Confirmed adjuster fax" } : null); }} style={{ padding: 10, width: "100%", minWidth: 0, boxSizing: "border-box", font: "inherit" }} /></label> : selection !== "" && chosen ? <>
      {chosen.method === "email" ? <p style={{ margin: 0, overflowWrap: "anywhere" }}>Email: {chosen.destination}. This selection does not send an email. Send the signed packet through your email service and record delivery.</p> : null}
      {chosen.phone ? <small>Telephone for questions: {chosen.phone}</small> : null}
    </> : null}
    <small><a href="https://mindbill.org" target="_blank" rel="noopener noreferrer">Powered by MindBill</a></small>
  </fieldset>;
}

// packages/angular/src/lib/rfa-authorization-destination.component.ts
import { Component, EventEmitter, Input, OnChanges, Output } from "@angular/core";
import { CommonModule } from "@angular/common";
import { normalizeRfaFax, rfaAuthorizationDestinations, rfaAuthorizationGuidance, type BillClaimsAdministratorDirectory, type RfaAuthorizationDestinationOption } from "@mindbill/browser";
import { mindBillAngularAppearanceStyle, type MindBillAngularAppearance } from "./appearance";
import { treatmentDraftKey } from "./submission-treatment";

/** A destination choice never signs, transmits, or substitutes a telephone number for fax. */
@Component({
  selector: "mindbill-rfa-authorization-destination", standalone: true, imports: [CommonModule],
  template: `<section class="rfa-destination" [ngStyle]="theme" aria-label="RFA authorization destination">
    <h3>Authorization destination</h3>
    <p role="status">{{ guidance }}</p>
    @if (sourceUrl) { <p class="source"><a [href]="sourceUrl" target="_blank" rel="noopener noreferrer">Directory source</a> @if (directory?.authorizationSource?.observedAt) { · Observed {{ directory?.authorizationSource?.observedAt }} }</p> }
    <fieldset [disabled]="disabled || loading"><legend>Confirm where this request should go</legend>
      @for (option of options; track $index; let index = $index) {
        <label class="choice"><input type="radio" [name]="radioName" [checked]="choice === '' + index" (change)="choose('' + index)" />
          <span><strong>{{ option.label }}</strong><span>{{ option.method === 'email' ? 'Email' : 'Fax' }}: {{ option.destination }}</span>@if (option.phone) { <small>Telephone: {{ option.phone }}</small> }</span>
        </label>
      }
      <label class="choice"><input type="radio" [name]="radioName" [checked]="choice === 'manual'" (change)="choose('manual')" /><span>Enter a fax confirmed with the handling adjuster</span></label>
      @if (choice === 'manual') {
        <label class="manual">Authorization fax<input type="tel" [value]="manualFax" (input)="setManualFax($any($event.target).value)" placeholder="+1 415 555 0100" /></label>
        <label class="choice"><input type="checkbox" [checked]="manualConfirmed" (change)="confirmManual($any($event.target).checked)" /><span>I confirmed this fax is the authorization destination for this claim.</span></label>
        @if (manualFax && !validManualFax) { <p role="alert">Enter a complete fax number without extensions or telephone notes.</p> }
      }
    </fieldset>
    @if (selected?.method === 'email') { <p class="notice">Download the signed packet, send it through your authorized email service, then record delivery. Selecting this address does not send email.</p> }
    @if (selected?.method === 'fax') { <p class="notice">Review the signed packet and confirm transmission in your delivery workflow. Selecting this fax does not send it.</p> }
  </section>`,
  styles: [`.rfa-destination{font-family:var(--font,Arial,sans-serif);color:var(--t,#263645);min-width:0}h3{font-size:17px;margin:0 0 10px}p{font-size:14px;line-height:1.55}fieldset{border:1px solid var(--b,#d9e2e9);border-radius:8px;padding:15px}legend{font-weight:600;font-size:14px}.choice{display:flex;gap:10px;align-items:flex-start;font-size:14px;line-height:1.5;padding:10px 0;cursor:pointer}.choice input{flex:none;margin-top:4px}.choice>span{display:grid;gap:3px;overflow-wrap:anywhere;min-width:0}small,.source{color:var(--m,#607181);font-size:12px}.manual{display:grid;gap:7px;font-size:14px;margin:8px 0}.manual input{font:inherit;border:1px solid #c8d3dc;border-radius:6px;padding:10px;width:100%;box-sizing:border-box}.notice{padding:12px;background:#f4f8fb;border-radius:6px}a{color:var(--a,#1677cf)}`],
})
export class MindBillRfaAuthorizationDestinationComponent implements OnChanges {
  @Input({ required: true }) contextKey = "";
  @Input() directory: BillClaimsAdministratorDirectory | null = null;
  @Input() loading = false;
  @Input() error: string | null = null;
  @Input() disabled = false;
  @Input() appearance?: MindBillAngularAppearance;
  @Output() destinationChange = new EventEmitter<RfaAuthorizationDestinationOption | null>();
  options: RfaAuthorizationDestinationOption[] = [];
  selected: RfaAuthorizationDestinationOption | null = null;
  choice = "";
  manualFax = "";
  manualConfirmed = false;
  private previousKey = "";
  get radioName() { return `rfa-destination-${this.contextKey}`; }
  get theme() { return mindBillAngularAppearanceStyle(this.appearance); }
  get validManualFax() { return normalizeRfaFax(this.manualFax); }
  get guidance() { return this.loading ? "Loading authorization contacts…" : this.error ? "Directory details are unavailable. Confirm a destination with the handling adjuster." : rfaAuthorizationGuidance(this.directory); }
  get sourceUrl(): string | null {
    try { const url = new URL(this.directory?.authorizationSource?.url ?? ""); return ["https:", "http:"].includes(url.protocol) ? url.href : null; } catch { return null; }
  }
  ngOnChanges() {
    const key = treatmentDraftKey({ context: this.contextKey, directory: this.directory, loading: this.loading, error: this.error });
    if (key === this.previousKey) return;
    this.previousKey = key;
    this.options = this.loading || this.error ? [] : rfaAuthorizationDestinations(this.directory);
    this.choice = ""; this.manualFax = ""; this.manualConfirmed = false;
    this.emit(null);
  }
  choose(choice: string) {
    if (this.disabled || this.loading) return;
    this.choice = choice; this.manualConfirmed = false;
    this.emit(choice === "manual" ? null : this.options[Number(choice)] ?? null);
  }
  setManualFax(value: string) { this.manualFax = value; this.manualConfirmed = false; this.emit(null); }
  confirmManual(confirmed: boolean) {
    this.manualConfirmed = confirmed;
    const destination = this.validManualFax;
    this.emit(confirmed && destination ? { method: "fax", destination, label: "Confirmed handling adjuster fax" } : null);
  }
  private emit(value: RfaAuthorizationDestinationOption | null) { this.selected = value; this.destinationChange.emit(value); }
}
